apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend
          image: hadyaziz05/backend:v8
          ports:
            - containerPort: 4000   
          env:
            - name: MONGODB_URI
              value: "mongodb://host.docker.internal:27017/myDB"
            - name: PORT
              value: "4000"  
